/*
 * This file was generated by the Gradle 'init' task.
 */

import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
    application
    id("com.github.johnrengelman.shadow") version "5.2.0"
}

version = "0.0.1"

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
}

dependencies {
    implementation("com.isda:cdm:2.108.1")
    implementation("org.hyperledger.fabric-chaincode-java:fabric-chaincode-shim:2.+")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
}

application {
    mainClassName = "org.hyperledger.fabric.contract.ContractRouter"
}
tasks {
    "shadowJar"(ShadowJar::class) {
        baseName = "playground.trade.lifecycle.chaincode"
        version = null
        classifier = null
        manifest {
            attributes(mapOf("Main-Class" to "org.hyperledger.fabric.contract.ContractRouter"))
        }
    }
}
