/*
 * This file was generated by the Gradle 'init' task.
 */


dependencies {

    implementation("com.google.guava:guava:29.0-jre")
    implementation("org.hyperledger.fabric:fabric-gateway-java:2.1.1")
}
