/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    application
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
}

application {
    mainClassName = "com.org.preTrade.app"
}
dependencies {

    implementation("com.google.guava:guava:29.0-jre")
    implementation("com.isda:cdm:2.108.1")
    implementation("org.hyperledger.fabric:fabric-gateway-java:2.1.1")
}
